# Catalog defines shared dependency versions across the workspace.
# This ensures consistent versions of prettier and its plugins are used
# throughout all packages in the monorepo.
#
# Documentation: https://pnpm.io/catalogs
catalog:
  "prettier-plugin-css-order": "^2.1.2"
  "prettier-plugin-packagejson": "^2.5.19"
  "prettier-plugin-sort-json": "^4.1.1"
  "prettier": "^3.6.2"

# Defines which directories contain packages that should be included in your
# pnpm workspace (monorepo).
#
# Documentation: https://pnpm.io/workspaces#packages
#
# Example: Shared dependencies: Packages can reference each other using
# workspace protocol (e.g., "my-package": "workspace:*").
packages:
  - "apps/*"
  - "packages/*"
