/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Demo1RouteImport } from './routes/demo-1'
import { Route as SidebarRouteRouteImport } from './routes/_sidebar/route'
import { Route as SidebarIndexRouteImport } from './routes/_sidebar/index'
import { Route as SidebarComponentsSlugRouteImport } from './routes/_sidebar/components/$slug'

const Demo1Route = Demo1RouteImport.update({
  id: '/demo-1',
  path: '/demo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarComponentsSlugRoute = SidebarComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarIndexRoute
  '/demo-1': typeof Demo1Route
  '/components/$slug': typeof SidebarComponentsSlugRoute
}
export interface FileRoutesByTo {
  '/demo-1': typeof Demo1Route
  '/': typeof SidebarIndexRoute
  '/components/$slug': typeof SidebarComponentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/demo-1': typeof Demo1Route
  '/_sidebar/': typeof SidebarIndexRoute
  '/_sidebar/components/$slug': typeof SidebarComponentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo-1' | '/components/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/demo-1' | '/' | '/components/$slug'
  id:
    | '__root__'
    | '/_sidebar'
    | '/demo-1'
    | '/_sidebar/'
    | '/_sidebar/components/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  Demo1Route: typeof Demo1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-1': {
      id: '/demo-1'
      path: '/demo-1'
      fullPath: '/demo-1'
      preLoaderRoute: typeof Demo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/': {
      id: '/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/components/$slug': {
      id: '/_sidebar/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof SidebarComponentsSlugRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarIndexRoute: typeof SidebarIndexRoute
  SidebarComponentsSlugRoute: typeof SidebarComponentsSlugRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarIndexRoute: SidebarIndexRoute,
  SidebarComponentsSlugRoute: SidebarComponentsSlugRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  Demo1Route: Demo1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
